#!/usr/bin/bash
#
# Script to run mdj-cli.
# Put this script into a directory in your PATH.  A good one
# might be "~/bin". 
#
#
# Auth: Brad Willcott - 9/03/2020
#

java -jar /home/bwillcott/apps/mdj-cli/mdj-cli-*.jar "$@"
# Done
